feat(zsh): autoload plugin functions in init script

diff --git a/src/dot_config/shell/zsh/functions/executable_print-plugin-script b/src/dot_config/shell/zsh/functions/executable_print-plugin-script
--- a/src/dot_config/shell/zsh/functions/executable_print-plugin-script
+++ b/src/dot_config/shell/zsh/functions/executable_print-plugin-script
@@ -4,28 +4,44 @@
 # sourcing. This helper is only meant to be called from load-plugins, or for
 # debugging.
 #
-# Source: https://github.com/mattmc3/zsh_unplugged/blob/main/antidote.lite.zsh
+# Sources:
+#  - https://github.com/mattmc3/zsh_unplugged/blob/main/antidote.lite.zsh
+#  - https://github.com/sorin-ionescu/prezto/blob/master/init.zsh
 
 emulate -L zsh
-setopt extendedglob globdots nomonitor
+setopt extendedglob globdots
 
-local plugin
+local plugin init init_dir
 local inits=()
+local funcs=()
 for plugin in $@; do
+    # Find the plugin init script or functions dir.
     inits=(
-        {$ZPLUGINDIR,$XDG_CACHE_HOME/zsh-plugins}/$plugin/${plugin:t}.{plugin.zsh,zsh-theme,zsh,sh}(N)
-        $ZPLUGINDIR/$plugin/*.{plugin.zsh,zsh-theme,zsh,sh}(N)
-        $ZPLUGINDIR/$plugin(N)
-        ${plugin}/*.{plugin.zsh,zsh-theme,zsh,sh}(N)
-        ${plugin}(N)
+        $ZPLUGINDIR/$plugin/${plugin:t}.{plugin.zsh,zsh-theme,zsh,sh}(.N)
+        $ZPLUGINDIR/$plugin/*.{plugin.zsh,zsh-theme,zsh,sh}(.N)
+        $ZPLUGINDIR/$plugin(.N)
+        $plugin/*.{plugin.zsh,zsh-theme,zsh,sh}(.N)
+        $plugin(.N)
+        $ZPLUGINDIR/$plugin/functions(/FN)
+        $plugin/functions(/FN)
     )
-    if (( $#inits == 0 )); then
-        log:error "No init found for plugin: $plugin"
+    if (($#inits == 0)); then
+        printf '[error] Plugin not found: %s' $plugin >&2
         continue
     fi
 
-    plugin=$inits[1]
-    # Add functions to $fpath.
-    echo "fpath+=($plugin/functions(-/FN))"
-    echo "source:file $plugin"
+    init=${inits[1]}
+    init_dir=${init:h}
+
+    # Prepend functions to fpath and autoload them.
+    funcs=($init_dir/functions/^([_.]*|prompt_*_setup|README*|*~)(.N:t))
+    if (($#funcs > 0)); then
+        echo "fpath=($init_dir/functions \$fpath)"
+        echo autoload -Uz $funcs
+    fi
+
+    # Source the plugin.
+    if [ -r $init ]; then
+        echo "source:file $init"
+    fi
 done
