refactor: manage some dotfiles with chezmoi

diff --git a/src/dot_bash_profile b/src/dot_bash_profile
--- a/src/dot_bash_profile
+++ b/src/dot_bash_profile
@@ -9,16 +9,10 @@
 # https://www.gnu.org/software/bash/manual/bash.html#Bash-Startup-Files
 #
 
-DOTFILES_DIR="${XDG_DATA_HOME:-$HOME/.local/share}/dotfiles"
-
 # Load .bashrc so login shells behave the same as non-login shells (it isn't
 # sourced automatically by login shells).
-bashrc="$DOTFILES_DIR/configs/.bashrc"
-# shellcheck disable=1090
-if [ ! -r "$bashrc" ] || ! source "$bashrc"; then
-    printf '[error] %s\n' "file not loaded: $bashrc" >&2
-    # Fall back to the default path.
-    source "$HOME/.bashrc"
+# shellcheck disable=1091
+if [ ! -r "$HOME/.bashrc" ] || ! source "$HOME/.bashrc"; then
+    printf '[error] %s\n' "file not loaded: $HOME/.bashrc" >&2
     return 1
 fi
-unset bashrc
